repository: sachabruttin/CosmostDbExplorer
theme: jekyll-theme-cayman

title: Cosmos DB Explorer

show_downloads: "false"
github:
  tar_url: http://github.com/sachabruttin/CosmosDbExplorer/tarball/master
  zip_url: http://github.com/sachabruttin/CosmosDbExplorer/zipball/master

google_analytics: UA-45847559-1

plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag

# seo-tag plugin
logo: /assets/documentDbColor.png